WIP Rondb 332
logicalclocks/irondb pull request #249
Opened 2023-04-05 10:45 UTC by smkniazi

2023-04-06 10:01 UTC, olapiv requested changes
I gave up after seeing all the interfaces. I'll continue again after you've addressed my comments, then I'll actually look into the logic fixes.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/data-access-rondb/src/rdrs-hopsworks-dal.cpp
> +  } while (true);
This is the third time I've seen this pattern - I'm sure you can extract it?

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/README.md
> +                 "APIKeyParameters": {
"Parameters" is kinda implicit

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/structs.go
> +var _ Validater = (*TLS)(nil)
Neat idea, but I don't think this is going to help, unless you dynamically run through every struct through a function that requires a Validator. I would just remove it.

Also, Validater -> Validator

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/getters_setters.go
> +	return &globalConfig
No, if you do this, you have to handle concurrency issues writing to the struct.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +var _ handlers.Handler = (*Handler)(nil)
This is already taken care of in the `Handle` function in `internal/handlers/handler.go`.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey.go
> +}
I think unless you're gonna implement a dummy right away (and there is a use-case for creating one), building an interface is a waste of space and makes things more difficult to read.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +var _ apikey_cache.HWAPIKeyCache = (*HWAPIKeyCache)(nil)
Use functions that require interfaces for implicit checks rather than creating this code everywhere. See `Handle()` method in `handler.go`.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
You're setting this globally for the instantiation of a local object?

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +func NewAPIKeyCache() apikey_cache.HWAPIKeyCache {
The return value just mystifies things. You can always convert to an interface, it's more risky to return to a struct though.

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +		return
Why not return an error and let the caller decide what to do?

2023-04-06 10:01 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +func (h *Handler) Validate(request interface{}) error {
These handlers are very light-weight, since they just contain pointers. I'd remove the complexity of making them pointers here as well (no nil checks necessary).

2023-04-06 11:19 UTC, smkniazi reviewed
I have pushed some changes. 
I have not accommodated the change requests for checking if a struct implements an interface as it helps https://go.dev/doc/faq#implements_interface

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/rdrs-hopsworks-dal.cpp
> +  } while (true);
Nope. what is the issue here

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/README.md
> +                 "APIKeyParameters": {
agree.

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/config/getters_setters.go
> +	return &globalConfig
We read the conf in different places in the server and there is no need to return a copy of it. We should avoid creating objects as much as we can to reduce work for GC
The conf is only modified in the tests and the places where it is modified are single-threaded.

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/config/structs.go
> +var _ Validater = (*TLS)(nil)
Trying to follow go naming convention here. The interface for Validate will be Validater. 

I will not remove the above code as the purpose is to throw early compiler errors  if the interface change

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +func (h *Handler) Validate(request interface{}) error {
every additional copy of an object counts.

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +var _ handlers.Handler = (*Handler)(nil)
Yes, kinda but not fully. It is better to have such checks to find unused and unimplemented methods

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey.go
> +}
It is needed. This interface will be used to build another API cache specific to Allstate.

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
I do not see what is wrong with setting the seed here

2023-04-06 11:19 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +		return
This is async job to update the cache. It can only log the errors

2023-04-06 11:43 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/getters_setters.go
> +	return &globalConfig
Yeah I understand the issue. What about parallel tests in the future? Or tests running after that test?

I was initially thinking of creating a local config object at the top and then passing it down, but then infinitely many methods/structs would need the config. Also wouldn't solve the server/client conflict in integration tests. We'll have the same problem with zap Logger.

If you want to return a pointer, then just remove the Getter and capitalise the variable?

2023-04-06 11:48 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/structs.go
> +var _ Validater = (*TLS)(nil)
If I remove a validation method, it probably has a reason.

If add a struct field to Config, nothing will happen. I have to actively add another line here as well. So basically the reviewer is the "compilation error", just like now.

2023-04-06 11:48 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +func (h *Handler) Validate(request interface{}) error {
Ok

2023-04-06 11:49 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +var _ handlers.Handler = (*Handler)(nil)
Why not fully? Try to remove the Validate() method and see what happens.

2023-04-06 11:52 UTC, olapiv commented on storage/ndb/rest-server/data-access-rondb/src/rdrs-hopsworks-dal.cpp
> +  } while (true);
Replication. It's fine if it's too complicated.

2023-04-06 11:54 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey.go
> +}
Then add a comment that we need this to satisfy different API key systems. Wouldn't be happy to see AllState-specific code in the RonDB repository though. Rather a general abstraction of API key systems.

2023-04-06 11:55 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
Then at least say why.

2023-04-06 11:56 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +		return
But then let the worker decide that. You don't even have to do 'err :=' if you don't want to.

2023-04-06 12:06 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/getters_setters.go
> +	return &globalConfig
Actually, I would recommend this:
- return a value
- get the value once at server instantiation and pass its pointer to all handlers

If you really want to change the config in tests, you have to restart the server.

2023-04-06 12:45 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/rdrs-hopsworks-dal.cpp
> +  } while (true);
I can get rid of it using MACROS but not in this PR

2023-04-06 12:49 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
to randomize ...

2023-04-06 12:53 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
To randomise what? Why is it necessary?

2023-04-06 15:45 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/rdrs-hopsworks-dal.cpp
> +  } while (true);
fixed it

2023-04-06 15:45 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/config/structs.go
> +var _ Validater = (*TLS)(nil)
removed it

2023-04-06 15:45 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/config/getters_setters.go
> +	return &globalConfig
reverted this change

2023-04-06 15:45 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/handlers/batchpkread/handler.go
> +var _ handlers.Handler = (*Handler)(nil)
reverted this change

2023-04-06 15:46 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +var _ apikey_cache.HWAPIKeyCache = (*HWAPIKeyCache)(nil)
reverted this change

2023-04-06 15:46 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/hw_apikey_cache/hw_api_cache.go
> +	rand.Seed(time.Now().Unix())
moved it to unit test, which is the correct place

2023-04-06 15:47 UTC, smkniazi reviewed
pushed all the changes

2023-04-12 12:26 UTC, olapiv requested changes

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/config/structs.go
> +}
Remove this

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/dal/heap/heap.go
> +		log.Errorf("Shutting down heap. Number of free buffers do not match. Expecting: %d, Got: %d.",
You're not "shutting down" anything afterwards?

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/integrationtests/initialiase_tests.go
> +		index++
Instead of using `cleanupFNs := make([]*func(), 10)`, use `cleanupFNs := []func(){}` and then
`cleanupFNs = append(cleanupFNs, cleanupX)`, then you don't have to keep track of the index. You can curry the function, such as:

```go
cleanupWrapper := func(cleanupFNs func()) {
        return func () {
            // clean up in reverse order
            for i := len(cleanupFNs) - 1; i >= 0; i-- {
                if cleanupFNs[i] != nil {
                    (cleanupFNs[i])()
                }
            }
        }
 }
```

then cleanupFNs doesn't have to be defined from the start.

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/integrationtests/initialiase_tests.go
> +	}
I think we use this pattern in other parts of the code as well - you could extract it, it looks a bit hacky here.

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/integrationtests/initialiase_tests.go
> +	cleanupFNs[index] = &apiKeyCleanup
Just reference `apiKeyCache.Cleanup`

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/integrationtests/initialiase_tests.go
> +		cleanupFNs[index] = &fileCloser
Again, just reference `f.Close`.

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/integrationtests/initialiase_tests.go
> -				stats.BuffersCount, stats.FreeBuffers)
You don't want to include this in the cleanup for a check?

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey.go
> +var _ APIKeyCacher = (*APIKeyCache)(nil)
This won't be necessary, since you use the interface for the Handlers.

2023-04-12 12:26 UTC, olapiv commented on storage/ndb/rest-server/rest-api-server/internal/security/apikey/apikey_cache/apikey_cache.go
> +}
Why is this an interface?

2023-04-12 12:52 UTC, merged