RONDB-288: Use Faster Base64 library
logicalclocks/irondb pull request #283
Opened 2023-05-04 16:39 UTC by olapiv

2023-05-04 16:40 UTC, olapiv commented
Will probably add benchmark unit tests in a different PR.

2023-05-08 10:57 UTC, smkniazi reviewed
I did not get why we have to throw an error here ```if (unlikely(result == 0))```

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    const int maxEncodedSize = ((4 * BINARY_MAX_SIZE_IN_BYTES_DECODED) / 3);
BINARY_MAX_SIZE_IN_BYTES_DECODED -> BINARY_MAX_SIZE_IN_BYTES

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    int result = base64_decode(encoded_str, encoded_str_len, (char *)&pk[0], &outlen, 0);
reinterpret_cast<char *>(pk)

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    if (unlikely(result == 0)) {
why "0" is considered an error here? https://github.com/aklomp/base64/blob/e77bd70bdd860c52c561568cffb251d88bba064c/lib/lib.c#L163

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    const int maxEncodedSize = ((4 * KEY_MAX_SIZE_IN_BYTES_DECODED) / 3);
KEY_MAX_SIZE_IN_BYTES_DECODED --- > KEY_MAX_SIZE_IN_BYTE

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    int result = base64_decode(encoded_str, encoded_str_len, (char *)(&pk[0] + additional_len), &outlen, 0);
reinterpret_cast<char *>(pk + additional_len)

2023-05-08 10:57 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    if (unlikely(result == 0)) {
same as above, doesn't zero represent a successful operation

2023-05-09 09:46 UTC, smkniazi approved these changes, later dismissed

2023-05-09 14:19 UTC, smkniazi requested changes

2023-05-09 14:19 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    char pk[KEY_MAX_SIZE_IN_BYTES];
this one (line 395) was not supposed to change. KEY_MAX_SIZE_IN_BYTES --> KEY_MAX_SIZE_IN_BYTES_DECODED

2023-05-09 14:19 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/db-operations/pk/common.cpp
> +    char pk[BINARY_MAX_SIZE_IN_BYTES];
line 349 was not supposed to change. BINARY_MAX_SIZE_IN_BYTES --> BINARY_MAX_SIZE_IN_BYTES_DECODED

2023-05-12 13:07 UTC, mronstro approved these changes

2023-05-12 13:18 UTC, smkniazi approved these changes

2023-05-12 13:20 UTC, merged