Rondb 442
logicalclocks/irondb pull request #349
Opened 2023-08-07 09:14 UTC by smkniazi

2023-08-09 08:16 UTC, kennethmhc requested changes

2023-08-09 08:16 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/internal/servers/grpc/batch_pk_read.go
> +	defer s.rdrsMetrics.EndPointMetrics.AddResponseTime(config.BATCH_OPERATION, "GRPC", float64(time.Now().UnixNano()-start))
The metrics need to be put at the end because the parameters are evaluated at the time of calling the defer. Also would be good to use a constant for `GRPC`

2023-08-09 08:16 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/internal/metrics/metrics.go
> +	metrics := EndPointMetrics{}
`protocol` should not contain `_http`

2023-08-09 15:18 UTC, smkniazi reviewed
please re-review it

2023-08-10 07:36 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/internal/servers/rest/server.go
> +		handerNameSplit := strings.Split(c.HandlerName(), ".")
```suggestion
		handlerNameSplit := strings.Split(c.HandlerName(), ".")
```

2023-08-10 07:43 UTC, kennethmhc approved these changes
LGTM! Just some typo

2023-08-10 11:48 UTC, merged