[FSTORE-982] Adopt serving key in feature store Rest API
logicalclocks/irondb pull request #353
Opened 2023-08-14 12:17 UTC by kennethmhc

2023-08-14 14:03 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/internal/dal/operations_feature_store.go
> -	var n_pk = int(fg.num_pk)
removed primary key

2023-08-14 14:03 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/resources/testdbs/fixed/hopsworks_34.sql
> +CREATE TABLE `users` (
Update schema for hopsworks 3.4

2023-08-16 17:26 UTC, smkniazi requested changes

2023-08-16 17:26 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/feature_store/feature_store.cpp
> +  assert(TRAINING_DATASET_FEATURE_NAME_SIZE ==
wrong constant add new Constants for "serving_key" table 
{TABLE_NAME}_{COLUMN_NAME}_SIZE

2023-08-16 17:26 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/feature_store/feature_store.h
> +  char feature_name[TRAINING_DATASET_FEATURE_NAME_SIZE];
wrong constants. add new Constants for "serving_key" table
{TABLE_NAME}_{COLUMN_NAME}_SIZE

2023-08-16 17:26 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/feature_store/feature_store.cpp
> +      // prefix
wrong comment. //join on

2023-08-16 17:26 UTC, smkniazi commented on storage/ndb/rest-server/rest-api-server/internal/feature_store/metadata.go
> +	PrimaryKeyMap       []*dal.ServingKey
Why is "ServingKey" struct defined in "dal" package while other structs are defined here?

2023-08-17 06:28 UTC, kennethmhc commented on storage/ndb/rest-server/data-access-rondb/src/feature_store/feature_store.cpp
> +  assert(TRAINING_DATASET_FEATURE_NAME_SIZE ==
It is because the feature name in serving key is coming from `TRAINING_DATASET_FEATURE` and they should always have the same value.

2023-08-17 06:35 UTC, kennethmhc commented on storage/ndb/rest-server/rest-api-server/internal/feature_store/metadata.go
> +	PrimaryKeyMap       []*dal.ServingKey
Because `ServingKey` can be reused in `metadata.go` while the other struct required some transformation from the struct in `dal`

2023-08-17 08:48 UTC, smkniazi commented on storage/ndb/rest-server/data-access-rondb/src/feature_store/feature_store.cpp
> +  assert(TRAINING_DATASET_FEATURE_NAME_SIZE ==
I do not see any connection between the two tables serving_key and tarining_dataset_feature in the schema files. Right now it is possible that someone will update the lengths of the columns in `serving_key` independent of `training_dataset_feature`. Please add separate constants for "serving key"

2023-08-17 09:48 UTC, smkniazi approved these changes

2023-08-17 09:48 UTC, merged