RONDB-576, RONDB-593 mtr integration, Read configs from file
logicalclocks/irondb pull request #436
Opened 2024-01-25 16:21 UTC by 641bill

- Enable mtr testing
- Enable reading configs from files
- Refactor the code
- Reduce memory allocation by having per thread string buffer, parser and document
- Comment out the reconnection tests before they are fixed

2024-02-22 10:21 UTC, smkniazi commented
Linux build fails

2024-02-23 13:04 UTC, smkniazi commented
rdrs_dal_ext.hpp
=============
the name of the file is very confusing. Can we call it BufferManager.cpp/hpp

Can we move the RS_Buffer from rdrs-dal.h to here ?

We discussed it before. The main idea of using a buffer manager was to reduce the
number of memory allocations and de-allocations. With the current implementation,
we allocate and de-allocate memory for each request. Each request buffer is 1MB in size.
It will have a big performance impact and lead to memory defragmentation.
Can't we have a global memory buffer pool?  We will borrow buffers from the pool and return the buffers

2024-02-23 13:05 UTC, smkniazi commented
All Files
======
There are unsed imports in many files.

2024-02-23 13:06 UTC, smkniazi commented
Build
====
Does not build on linux

2024-02-23 13:08 UTC, smkniazi commented
String and pointers
=====
change all std::vector<char> to char* or std::string. std::vector<char>  is not the most common or idiomatic way to handle strings in cpp. Use char* or std::string.
Do not pass pointers as references. Use simple pointers e.g.
func(ptr *&char)  // no no
func(ptr *char) // yes yes

2024-02-23 13:08 UTC, smkniazi requested changes

2024-02-23 13:08 UTC, smkniazi commented on mysql-test/suite/rdrs2/include/have_rdrs.inc
> +
the first version of rdrs was written in the two languages and the part written in ccp was built as a shared lib. this shared lib was then loaded by the go application
it is no longer the case for rdr2. you can skip this part

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/CMakeLists.txt
> +
change rdrs2_shared ====> ${PROJECT_NAME}_shared
more importantly why we are creating a shared lib for rdrs2. is it used anywhere

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +  return RS_Status();
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +  return RS_Status();
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status REST::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status TestParameters::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status TLS::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status APIKey::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status Security::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status Testing::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status MySQL::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +RS_Status MySQLServer::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/log.cpp
> +RS_Status LogConfig::validate() {
Add
// TODO Implement Me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +  size_t currentThreadIndex = DEFAULT_NUM_THREADS;
what?
thread id is not applicable here as
this code can be called from any where
it can be called from drogon thread, main
or a test thread.
you can have a dedicated json parser for
config only. it is ok that confing processing
is not efficient

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/encoding.cpp
> +  EN_Status status = copy_str_to_buffer(
// why are you converting string to a 'char' vector. This is very unintuitive.
// cant you just pass string.to_cstr().
//

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/encoding.cpp
> +      std::vector<char>(pkReadParams.path.table.begin(), pkReadParams.path.table.end()), reqBuff,
same as above

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/encoding.cpp
> +    status = copy_str_to_buffer(std::vector<char>(filter.column.begin(), filter.column.end()),
same as above.

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/encoding_helper.cpp
// EN_Status copy_str_to_buffer(char *src, size_t str_len, void *dst, uint32_t offset)
or some thing like that. no vector<char>

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +
// any particular reason why you are using "member initializer list" only for
// "parser" and not for other members like "doc". Is is even necessary?
// you can omit it.

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +
// can't you make them private members of the class? You are not using them outside json_parser.cpp

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +    handle_simdjson_error(error, doc[threadId], currentLocation);
return handle_simdjson_error(error, doc[threadId], currentLocation);
    // i think you want to return here and not continue processing after the error
    // same is true for all occurrences of handle_simdjson_error

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +    handle_simdjson_error(error, doc[threadId], currentLocation);
same as above.
Fix it in all other places

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.hpp
> +  simdjson::ondemand::parser parser[DEFAULT_NUM_THREADS + 1];
why +1

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.hpp
> +  simdjson::ondemand::document doc[DEFAULT_NUM_THREADS + 1];
why +1?

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.hpp
> +  /*
fix formating. too much padding

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/json_parser.hpp
> +  std::unique_ptr<char[]> &get_buffer(size_t threadId) {
//why not put the definition in cpp file to make this header cleaner?
//it is a matter of personal taste. So you can ignore it if you want

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/log.hpp
Add a comment

// TODO implement me

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/pk_data_structs.hpp
> +#include "src/constants.hpp"
unused header

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/pk_data_structs.hpp
>  #include "config_structs.hpp"
unused headers

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/pk_data_structs.hpp
the function setColumnData must not accept string as char vector. use char* or string

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/batch_pk_read_ctrl.cpp
>      resp->setStatusCode(drogon::HttpStatusCode::k400BadRequest);
drogon::HttpStatusCode::k400BadRequest -->  drogon::HttpStatusCode::k500InternalServerError

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/batch_pk_read_ctrl.cpp
>      resp->setStatusCode(drogon::HttpStatusCode::k400BadRequest);
make the same change in pk_read_ctrl.cpp

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/batch_pk_read_ctrl.cpp
> +  size_t length        = req->getBody().length();
// add a check for data length
// if req->getBody().length > buffersize {
//   throw error
// }

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/batch_pk_read_ctrl.cpp
> +  size_t length        = req->getBody().length();
make a similar change in pk_read_ctrl.cpp

2024-02-23 13:08 UTC, smkniazi commented on storage/ndb/rest-server2/server/src/batch_pk_read_ctrl.cpp
> +  strcpy(jsonParser.get_buffer(currentThreadIndex).get(), json_str);
// memcpy would be faster for large requests
make a similar change in pk_read_ctrl.cpp

2024-03-07 14:42 UTC, 641bill commented on storage/ndb/rest-server2/server/src/config_structs.cpp
> +  size_t currentThreadIndex = DEFAULT_NUM_THREADS;
Only the main thread can call this function and set the configs, so I set it to be a special number (DEFAULT_NUM_THREADS)

2024-03-07 14:42 UTC, 641bill commented on storage/ndb/rest-server2/server/CMakeLists.txt
> +
Some part of the integration tests in Go I copied to rest-server2 still depend on rdrs2 as a shared lib. We could get rid of the shared lib later when we don't need the Go tests completely. If I change this now it's some more unnecessary checks.

2024-03-07 14:48 UTC, 641bill commented
> # String and pointers
> change all std::vector to char* or std::string. std::vector is not the most common or idiomatic way to handle strings in cpp. Use char* or std::string. Do not pass pointers as references. Use simple pointers e.g. func(ptr *&char) // no no func(ptr *char) // yes yes

Changed copy_str_to_buffer to operate on strings instead. PKReadFilter.value is still a std::vector<char> because it's viewed as a byte array.

The only place with *& is 
RS_Status handle_simdjson_error(const simdjson::error_code &error,
                                simdjson::ondemand::document &doc, const char *&currentLocation),
which is because here the pointer needs to be updated, rather than the content the pointer points to.

2024-03-07 14:50 UTC, 641bill commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +
Probably not necessary

2024-03-07 14:51 UTC, 641bill commented on storage/ndb/rest-server2/server/src/json_parser.cpp
> +
They already are I think?

2024-03-07 15:05 UTC, 641bill commented on storage/ndb/rest-server2/server/src/json_parser.hpp
> +  simdjson::ondemand::parser parser[DEFAULT_NUM_THREADS + 1];
Because of the main thread parsing the config file

2024-03-11 10:07 UTC, 641bill commented on storage/ndb/rest-server2/server/src/pk_data_structs.hpp
It's meant to represent a byte vector, not a string

2024-03-20 12:25 UTC, smkniazi approved these changes

2024-03-20 12:35 UTC, merged