RONDB-592: API Key
logicalclocks/irondb pull request #457
Opened 2024-04-03 14:57 UTC by 641bill

- Add API Key authentication between execution and validation
- Enable API Key caching
- Add GoogleTest C++ tests for API key caching
- Adjust the MTR tests accordingly

@smkniazi

2024-06-10 08:00 UTC, smkniazi requested changes
[api-key-review.txt](https://github.com/user-attachments/files/15758661/api-key-review.txt)

2024-08-08 11:58 UTC, 641bill commented
Regarding the pthread locks:
- It's not easier to use ReadLock class to replace the explicit pthread locks since they need to be released before the function returns.

Order of Validate and Authenticate:
- Was trying to follow Go server's order

2024-08-14 11:10 UTC, smkniazi submitted a review, later dismissed
Please create a PR for improving API cache using single or fixed number of multiple update threads

2024-08-15 09:35 UTC, mronstro approved these changes

2024-08-15 09:36 UTC, merged